### ISSUE TITLE
 Please add a recent study

### ISSUE THREAD

**Issue by 98brucelee** [lzz19980125/awesome-time-series-segmentation-papers#2]
Carpentier L, Feremans L, Meert W, et al. Pattern-based Time Series Semantic Segmentation with Gradual State Transitions[C]//Proceedings of the 2024 SIAM International Conference on Data Mining (SDM). Society for Industrial and Applied Mathematics, 2024: 316-324.

**Comment by lzz19980125** [comment]
Good paper，I will add it soon.
